name: Kernel Config Generation

on:
  workflow_dispatch:

env:
  TZ: Asia/Kolkata

jobs:
  generate-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4.2.2

      - name: Install Build Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git ccache build-essential bc bison flex libssl-dev libncurses-dev \
            liblz4-tool libzstd-dev zstd curl python3 unzip aria2 device-tree-compiler

      - name: Download and Sync Clang Toolchain
        run: |
          TOOLCHAIN_DIR="$HOME/toolchains/clang"
          mkdir -p "$TOOLCHAIN_DIR"
          cd "$TOOLCHAIN_DIR"
          curl -L "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main-kernel/clang-r563880.tar.gz" -o clang-toolchain.tar.gz
          tar -xvzf clang-toolchain.tar.gz

      - name: Generate Kernel .config
        run: |
          export PATH="$HOME/toolchains/clang/bin:$PATH"
          export KBUILD_BUILD_USER="Shreyash"
          export KBUILD_BUILD_HOST="nand"

          make distclean
          make -j$(nproc) O=out ARCH=arm64 \
            CC=clang \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=$HOME/toolchains/clang/bin/aarch64-linux-android- \
            AR=llvm-ar \
            HOSTCC=clang \
            HOSTCXX=clang++ \
            NM=llvm-nm \
            LLVM_DIS=llvm-dis \
            OBJCOPY=llvm-objcopy \
            READELF=llvm-readelf \
            OBJDUMP=llvm-objdump \
            OBJSIZE=llvm-size \
            STRIP=llvm-strip \
            LLVM=1 \
            LD=ld.lld \
            LLVM_IAS=1 \
            vendor/obiwan_defconfig


      - name: Upload .config File
        run: |
          CONFIG_PATH=$(find out/ -name ".config" | head -n 1)
          echo "Found config at: $CONFIG_PATH"
          mkdir -p config_upload
          cp "$CONFIG_PATH" config_upload/kernel.config
        shell: bash

      - name: Upload Kernel .config File Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: KernelConfig
          path: config_upload/kernel.config
